/*jshint maxlen:false */

define({
    CANCEL:                             "Cancel",
    CLEAR:                              "Clear",
    CLOSE:                              "Close",
    CONNECT:                            "Connect",
    ENTER_GIST_URL:                     "Enter a Gist url",
    ERROR:                              "Error",
    ERROR_API_REQ_FAIL:                 "API request failed: ",
    ERROR_INVALID_AUTH_SCOPE:           "Token auth scope doesn't contain gist rights: ",
    ERROR_NO_AUTH_SCOPE:                "No auth scope received from API request.",
    ERROR_UNKNOWN:                      "Unknown error",
    ERROR_TOKEN_REQUIRED:               "Gist access token is required to use this feature.",
    EXPORT_TO_GIST:                     "Export to Gist",
    GIST_AUTH_HINT:                     "You need to create an access token with \"gist\" rights here:",
    GIST_AUTHORIZATION:                 "Gist authorization",
    LOAD_SNIPPET_FROM_GIST:             "Load a snippet from Gist url",
    MSG_AUTH_SUCCESS:                   "Authorization successfull for ",
    MSG_CONNECTED_AS:                   "Connected as ",
    NO_SNIPPET_SELECTED:                "No snippet selected",
    NO_SNIPPETS_FOUND:                  "No snippets found",
    OK:                                 "OK",
    PERSONAL_TOKEN:                     "Personal access token",
    QUESTION:                           "Question",
    SETTINGS:                           "Settings",
    SNIPPET_DELETE_CONFIRM:             "Do you really wish to delete this snippet?",
    SNIPPET_DIALOG:                     "Snippet Dialog",
    SNIPPET_NAME:                       "Snippet Name"
});
