/*jshint maxlen:false */

define({
    CANCEL:                             "Annuler",
    CLEAR:                              "Effacer",
    CLOSE:                              "Fermer",
    CONNECT:                            "Connecter",
    DEFAULT_SNIPPET_DIRECTORY:          "Répertoire par défaut (où les nouveaux snippets sont enregistrés)",
    ENTER_GIST_URL:                     "Enntrer une adresse Gist",
    ERROR:                              "Erreur",
    ERROR_API_REQ_FAIL:                 "La requête vers l'API a échoué: ",
    ERROR_DEFAULT_GIST_NOTFOUND:        "Gist par défaut n'a pas été trouvé parmi vos Gists",
    ERROR_INVALID_AUTH_SCOPE:           "Le token du champ d'authentification ne contient pas de droits GIST:",
    ERROR_NO_AUTH_SCOPE:                "Aucune authentification reçu par la demande d'API..",
    ERROR_UNKNOWN:                      "Erreur inconnue",
    ERROR_TOKEN_REQUIRED:               "Le token d'accès Gist est nécessaire pour utiliser cette fonctionnalité.",
    EXPORT_TO_GIST:                     "Exporter vers Gist",
    EXTENSION_SHORTCUT:                 "Raccourci pour lancer un widget snippet",
    GIST_AUTH_HINT:                     "Vous devez créer un token d'accès avec les droits \"gist\" ici:",
    GIST_AUTHORIZATION:                 "Autorisation Gist",
    IMPORT_FROM_GIST:                   "Importer depuis Gist",
    IMPORT_FROM_GIST_QUESTION:          "Sélectionnez un URL pour télécharger des snippets ou laisser vide pour défaut",
    IMPORT_FROM_GIST_DELETE_LOCAL:      "Voulez-vous supprimer tous les snippets locals ?",
    IMPORT_SUCCESSFUL:                  "Import complété avec succès !",
    LOAD_SNIPPET_FROM_GIST:             "Chargez un snippet via une url Gist",
    MSG_AUTH_SUCCESS:                   "Autorisation réussie pour ",
    MSG_CONNECTED_AS:                   "Connecté en tant que",
    NO:                                 "Non",
    NO_SNIPPET_SELECTED:                "Aucun snippet selectionné",
    NO_SNIPPETS_FOUND:                  "Aucun snippets trouvés",
    OK:                                 "Ok",
    PERSONAL_TOKEN:                     "Token d'accès personnel",
    QUESTION:                           "Question",
    RESET_DEFAULT_DIR:                  "Réinitialiser le répertoire par défaut",
    RESET_DEFAULT_DIR_MSG:              "Voulez-vous vraiment réinitialiser le répertoire par défaut pour:",
    SETTINGS:                           "Paramètres",
    SNIPPET_DELETE_CONFIRM:             "Voulez-vous vraiment supprimer ce snippet ?",
    SNIPPET_DELETE_ALL_CONFIRM:         "Voulez-vous vraiment supprimer TOUS les snippets?",
    SNIPPET_DIALOG:                     "Boite de snippet",
    SNIPPET_DIRECTORIES:                "Répertoire du snippet",
    SNIPPET_DIRECTORY_ADD:              "Ajouter un répertoire snippet",
    SNIPPET_DIRECTORY_DELETE:           "Supprimer un répertoire snippet",
    SNIPPET_DIRECTORY_DELETE_CONFIRM:   "Voulez-vous vraiment supprimer ce répertoire snippet?",
    SNIPPET_NAME:                       "Nom du snippet",
    SPECIFY_DIRECTORY_FULLPATH:         "Spécifier le chemin complet du dossier:",
    TRIGGER_SNIPPET_MENU_ENTRY:         "Code Trigger du snippet",
    YES:                                "Oui"
});
