/*jshint maxlen:false */

define({
    CANCEL:                             "Abbrechen",
    CLEAR:                              "Leeren",
    CLOSE:                              "Schließen",
    CONNECT:                            "Verbinden",
    DEFAULT_SNIPPET_DIRECTORY:          "Standard Snippet Verzeichnis (wo neue Snippets gespeichert werden)",
    ENTER_GIST_URL:                     "Gebe eine Gist URL ein",
    ERROR:                              "Fehler",
    ERROR_API_REQ_FAIL:                 "API Anfrage fehlgeschlagen: ",
    ERROR_DEFAULT_GIST_NOTFOUND:        "Standard Gist wurde unter deinen Gists nicht gefunden",
    ERROR_INVALID_AUTH_SCOPE:           "Token Auth Scope enthält keine Gist Rechte:",
    ERROR_NO_AUTH_SCOPE:                "Keinen Auth Scope erhalten via API Anfrage.",
    ERROR_UNKNOWN:                      "Unbekannter Fehler",
    ERROR_TOKEN_REQUIRED:               "Gist Access Token erforderlich um diese Funktionen zu benutzen.",
    EXPORT_TO_GIST:                     "Exportiere als Gist",
    EXTENSION_SHORTCUT:                 "Tastenkürzel um Snippet Widget zu starten",
    GIST_AUTH_HINT:                     "Du musst hier einen Access Token mit \"gist\" Rechten erstellen:",
    GIST_AUTHORIZATION:                 "Gist Authorisierung",
    IMPORT_FROM_GIST:                   "Importiere von Gist",
    IMPORT_FROM_GIST_QUESTION:          "Wähle eine URL zum Download von Snippets oder lasse es leer für den Standard",
    IMPORT_FROM_GIST_DELETE_LOCAL:      "Möchtest du alle lokalen Snippets löschen?",
    IMPORT_SUCCESSFUL:                  "Import erfolgreich abgeschlossen!",
    LOAD_SNIPPET_FROM_GIST:             "Lade ein Snippet von Gist URL",
    MSG_AUTH_SUCCESS:                   "Authorisierung erfolgreich für ",
    MSG_CONNECTED_AS:                   "Verbunden als",
    NO:                                 "Nein",
    NO_SNIPPET_SELECTED:                "Kein Snippet ausgewählt",
    NO_SNIPPETS_FOUND:                  "Keine Snippets gefunden",
    OK:                                 "OK",
    PERSONAL_TOKEN:                     "Persönlicher Access Token",
    QUESTION:                           "Frage",
    RESET_DEFAULT_DIR:                  "Standard Snippet Verzeichnis zurücksetzen",
    RESET_DEFAULT_DIR_MSG:              "Möchtest du wirklich das Standard Snippet Verzeichnis zurücksetzen auf:",
    SETTINGS:                           "Einstellungen",
    SNIPPET_DELETE_CONFIRM:             "Möchtest du dieses Snippet wirklich löschen?",
    SNIPPET_DELETE_ALL_CONFIRM:         "Willst du wirklich ALLE Snippets löschen?",
    SNIPPET_DIALOG:                     "Snippet Dialog",
    SNIPPET_DIRECTORIES:                "Snippet Verzeichnisse",
    SNIPPET_DIRECTORY_ADD:              "Snippet Verzeichnis hinzufügen",
    SNIPPET_DIRECTORY_DELETE:           "Snippet Verzeichnis löschen",
    SNIPPET_DIRECTORY_DELETE_CONFIRM:   "Möchtest du dieses Snippet Verzeichnis wirklich löschen?",
    SNIPPET_NAME:                       "Snippet Name",
    SPECIFY_DIRECTORY_FULLPATH:         "Definiere Verzeichnis fullPath:",
    TRIGGER_SNIPPET_MENU_ENTRY:         "Code Snippet auslösen",
    YES:                                "Ja"
});
